openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://127.0.0.1:3008/v1
tags:
  - name: BRC-20
  - name: Inscriptions
  - name: Runes
paths:
  /btc/{network}/brc20/{ticker}/holders:
    get:
      tags:
        - BRC-20
      summary: holders
      description: Returns holders of a specific BRC-20 ticker
      operationId: btc-brc20-holders
      parameters:
        - name: network
          in: path
          description: BTC chain network
          required: true
          schema:
            type: string
        - name: ticker
          in: path
          description: BRC-20 ticker
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  unused_txes:
                    - pkscript: 512047891af93e1b6fe7bc9ae2d6ed4dcb1372e0d04f0d0d1beb4345765fbadc5ff4
                      wallet: bc1pg7y347f7rdh700y6uttw6nwtzdewp5z0p5x3h66rg4m9lwkutl6qtp7mwe
                      overall_balance: '100000000000000000000'
                      available_balance: '100000000000000000000'
                  block_height: 842921
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /btc/{network}/inscriptions/{id}:
    get:
      tags:
        - Inscriptions
      summary: inscription details
      description: Returns details of a specific inscription ID
      operationId: btc-inscription-details
      parameters:
        - name: network
          in: path
          description: BTC chain network
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: inscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Inscription ID not found
      security:
        - bearerAuth: []
  /btc/{network}/inscriptions/{id}/content:
    get:
      tags:
        - Inscriptions
      summary: inscription content
      description: Returns inscription content of a specific inscription ID
      operationId: btc-inscription-content
      parameters:
        - name: network
          in: path
          description: BTC chain network
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: inscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
            text/plain:
              example:
            application/octet-stream:
              example:
            image/jpeg:
              example:
            image/png:
              example:
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Inscription ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/{nameOrId}/holders:
    get:
      tags:
        - Runes
      summary: Rune holders
      description: Returns holders of a specific Rune name or ID
      operationId: btc-runes-holders
      parameters:
        - name: network
          in: path
          description: BTC chain network
          required: true
          schema:
            type: string
        - name: nameOrId
          in: path
          description: Rune name or ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
